apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluered
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/nirmiz/develop
    targetRevision: HEAD
    path: charts/bluered
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
