apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bluered
  name: bluered
  namespace: bluered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluered
  strategy: {}
  template:
    metadata:
      labels:
        app: bluered
    spec:
      containers:
      - image: nirmiz/bluered:latest
        name: bluered
        resources: {}
        envFrom:
          - configMapRef:
              name: config-color